### ISSUE TITLE
Secrets not filtered out of logging in all cases

### ISSUE THREAD

**Issue by charmander** [Weasyl/weasyl#245]
Introduced with Pyramid.

- When the request body is `multipart/form-data`, the CSRF token isn’t stripped
- `webob._parsed_cookies` contains the session token
- `webob._parsed_post_vars` isn’t stripped

**Comment by kfkitsune** [comment]
As long as we are stripping sensitive information from Sentry here, could we also ensure that we strip the ``passcheck`` field in ``form`` objects? @charmander, see your Gitter DMs for details, though given the event is 7 months old, I don't know if it was fixed yet. Just bringing it up since I recalled I saw this issue previously.

**Comment by kfkitsune** [comment]
Adding to this: ``X-Weasyl-Api-Key`` headers are not always stripped, and the API key effectively acts like a password. See Sentry ID ``8dc59e0b604842c08c2395704eb8a637`` in the logged headers section.

**Comment by charmander** [comment]
We don’t use Sentry or CSRF tokens anymore. For the stdout logging that’s now in place:

- `webob._parsed_cookies` is removed before logging
- [2c7fa3b640faa4ca86f679cf7dfe55c645501eaf 2022-06-11 :/Buffer request bodies in memory only, never to disk] prevents `webob._parsed_post_vars` from being created at all and request bodies aren’t otherwise logged
- `HTTP_COOKIE` is stripped
