### ISSUE TITLE
User search: Cannot search for e-mail addresses containing "+"

### ISSUE THREAD

**Issue by Hendikins** [Weasyl/weasyl#416]
Attempting to search by e-mail address for any string containing "+" throws an error.

Example request-id: 8a7061be725a464c9e6c3c3f3b8dfaa6-SF+Rg9h6

**Comment by charmander** [comment]
(As mentioned in the chat when this first came up, the workaround is to add a backslash before the `+`.)

**Comment by huntertur** [comment]
I took a look into this, and it seems like it is happening because of the use of the `~` regex operator on `username` and `email`: https://github.com/Weasyl/weasyl/blob/234cece1604e4adac06f09e13446c8593891150b/weasyl/moderation.py#L370

The two options I can think of are:
- Just use standard `ilike`, preventing any errors, but losing the regular expression searching capability and only being a simple substring.
- Note on the search page that these fields are regular expressions, and catch any regex errors on the backend to display a friendlier error message to the user.

Which would be preferred?

**Comment by charmander** [comment]
@huntertur `ILIKE` is probably fine; I haven’t needed any regex features, and we can always revisit that. Maybe specify `ESCAPE ''` so there actually are no error cases (Weasyl doesn’t accept `%` in e-mail addresses anyway), or automatically double ``\`` at the end of a pattern.
