### ISSUE TITLE
Adopt a code of conduct

### ISSUE THREAD

**Issue by weykent** [Weasyl/weasyl#47]
Since this project is open-source now. http://contributor-covenant.org/ is a good template.

**Comment by strain-113** [comment]
I like this a lot. Let's have a chance to review the template before including it though.

**Comment by weykent** [comment]
Absolutely. cc @skylerbunny @ikanimew on setting up an e-mail list for this, and then I'll check in a branch.

**Comment by skylerbunny** [comment]
In general, I like the idea of this project. We ought to discuss it some.

While in the strictest sense this 'waits on ops', the reason an email address is needed is the following, as per the contributor covenant documentation:

_Important! You must add a contact method to the placeholder in the document so that people **know how to report violations.**_ (bold emphasis mine)

Implicit to this is knowing _who_ to report them to, or to put it another way, who is supposed to be on the receiving end of this email address. This is not a technical issue, but a policy question that should be brought up to staff.

This desires discussion both in the 'Do we want to adopt this?' sense, and 'Who in our staff structure deals with violations?' senses.

support@, which already exists, logs a reference-able request to supportdesk and is visible to 'admins+'. It may very well be acceptable for this purpose. Once both points are ironed out, setting up a branch to move forward is pretty straightforward.

**Comment by weykent** [comment]
Cool. Since it's a staff issue, go talk to the staff.

**Comment by strain-113** [comment]
It's tricky because I'd like to distinguish between management of the site and management of the Open Source community. Although that is perhaps an unrealistic separation. Talk about it. In the meantime....

I've mulled over the license and I like it quite a bit. The language strikes a good balance between safe spaces and respecting differing opinions and it maintains a focus on civility. And it's nice that it's becoming an industry standard.

The only caveat I would take is that as our project often deals explicitly with sexual imagery I'd like to clarify that point. Maybe change the first bullet point to just:

 * Unwelcome sexual attention or advances

and add at the bottom of the list language like the following, adopted from http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Example_exception_to_policy:

Sexual imagery, language, or examples related to site content is permitted as long as (a) it is relevant to the topic of discussion (b) it is presented in a respectful manner, (c) effort has been made to find an alternative.

(c) might be unnecessary there.

Thoughts?

**Comment by skylerbunny** [comment]
codecov@ is now a live mailing list. We can add/remove addresses as we like (and much of this will relate to the discussion above), but it's a valid address!

**Comment by strain-113** [comment]
Can you make it conduct@ instead?

**Comment by strain-113** [comment]
And who is on that list?

**Comment by skylerbunny** [comment]
conduct@ is now the list. Currently it has on it myself, and Ikani. This is flexible; weasyl or non-weasyl addresses can be added/removed, to encompass the 'non staff' membership of the open source project.

**Comment by strain-113** [comment]
I would like at least one dev who isn't on staff on the list and potentially all members of the GitHub organization with owner privileges.

**Comment by weykent** [comment]
👍  to what @strain-113 said. This might work as a summon spell, but I think @iErrored would be a great addition to the list.

**Comment by strain-113** [comment]
Proposal in https://github.com/Weasyl/weasyl/pull/57

**Comment by iErrored** [comment]
That's fine by me, feel free to add me to the list.

**Comment by skylerbunny** [comment]
@iErrored Thanks, you've been added! Appreciate it.

**Comment by skylerbunny** [comment]
iErrored, Weykent, Ikanimew, Skylerbunny, strain-113, and charmander added to conduct@ as requested.

**Comment by strain-113** [comment]
Closed with #57. Let's hope it's a while before we have to enforce it.
