### ISSUE TITLE
No module named pathlib

### ISSUE THREAD

**Issue by Tigerjieer** [Weasyl/weasyl#474]
Hi. When trying to build Weasyl per README, something failed; mentioning a module `pathlib`. 
[output.txt](https://github.com/Weasyl/weasyl/files/2849758/output.txt) (issue near end)
I'm on Ubuntu 16.04 and VirtualBox 5.2.26.
Thanks.

**Comment by Tigerjieer** [comment]
Manually installing `pathlib` caused an invalid syntax
[output.txt](https://github.com/Weasyl/weasyl/files/2862406/output.txt)
.

**Comment by kfkitsune** [comment]
Hey there! Just wanted to check in on this, as I believe we've narrowed down the issue here.

It stems from the fact that we are explicitly disabling usage of binaries from PyPI over in the [Makefile](https://github.com/Weasyl/weasyl/blob/master/Makefile#L11); we're providing ``--no-binary :all:``. This is not a problem in an of itself to use locally built binaries, but as I'll outline below, it appears to be the cause of the issue, here.

- [``flake8``'s setup file](https://gitlab.com/pycqa/flake8/blob/master/setup.py) specifies ``entrypoints`` as a requirement. Flake8, itself, explicitly supports Py2/Py3.
- [``entrypoints``' pyproject.toml file](https://github.com/takluyver/entrypoints/blob/master/pyproject.toml) specifies that the build system requires ``flit`` for the build process. Entrypoints also supports Py2/Py3.
- [``flit``'s pyproject.toml file](https://github.com/takluyver/flit/blob/master/pyproject.toml), however, specifies that it does _not_ support Python 2, only 3. This is where the issue lies in the build chain.

I'll look into a MR for updating our Makefile to only exclude the binaries which @charmander mentioned over in Gitter to have previously caused problems; [the specific packages were](https://gitter.im/Weasyl/weasyl?at=5c63c1d64bafd97ca3e2ffde) ``sanpera``, ``psycopg2cffi``/``psycopg2``, and ``lxml``.

I'll try and do this tomorrow, if I have the chance to do so. In the meantime, you may be able to work around this locally if you edit [L11 of the Makefile](https://github.com/Weasyl/weasyl/blob/master/Makefile#L11), to instead read:

```
USE_WHEEL := --no-binary sanpera,psycopg2cffi,lxml
```

Bear in mind, I have not tested the above, but [per the documentation for ``pip``](https://pip.pypa.io/en/stable/reference/pip_install/#install-no-binary), this appears to be the correct syntax for forcing a local build for a set of binaries. I have, however, tested a clean Python 2 environment in Alpine Linux, both attempting to install via binaries and source, and trying to install ``flake8`` from source was the issue (due to ``flit`` not supporting Python 2.x, which itself was needed to build ``entrypoints``).

**Comment by kfkitsune** [comment]
@Tigerjieer, thanks for the report on this! You should be good to go for a rebuild via a ``vagrant provision`` now.

**Comment by Tigerjieer** [comment]
Works now. Thanks!
