### ISSUE TITLE
Switch to postgres 9.5+ upsert

### ISSUE THREAD

**Issue by weykent** [Weasyl/weasyl#51]
[Postgres 9.5 and greater have upsert](https://www.postgresql.org/docs/9.5/static/sql-insert.html), which would be great to use instead of catching constraint violations. This also makes it easier to move to using transactions in more places.

Waiting on a 9.5 deploy.

**Comment by strain-113** [comment]
More than just the deploy, I'd like to see a plan around the database upgrade and what downtime if any it might require.

**Comment by skylerbunny** [comment]
Well, I feel like a heel, seeing as this ticket asked for the deploy plan as well as the deploy itself (I missed that part of this request).

I did in any case try to keep our gitter channel up to date about the upgrade to db1 in production today. I realize this will be a post-mortem now rather than the advance plan, but it is what I planned in advance and the list I worked off of, expanded a bit for readability.

Ikani was available by SMS in case db1 needed vcenter related intervention in the middle of this upgrade. Rollback would be the use of the pg_dump backup which would be performed as the first step during this downtime.

* Our userbase was informed by @weasyldev and @weasyl's twitter account of the upgrade at -7 hours before upgrade time, and status.weasyl.com updated with the upcoming maintenance at that time. I outlined to gitter the length of the outage and a rough scale of the time the steps would take (10 minutes for backups, 20-25 minutes for the upgrade and vacuum processes). These times were taken from performing the same upgrade on db2, to determine estimates. I added additional time in case of other problems that might come up.
* Another tweet was sent to the userbase at -10 minutes as a reminder of the outage, and gitter.im's channel was also reminded. status.weasyl.com was put into a maintenance underway state at 11:00pm as the upgrade was started.

The upgrade itself involved the following steps:
* web1 and web2's workers were shut down. This brought up the 'Technical issue' error screen to users who attempted to access weasyl, and directed them to status.weasyl.com, which did show the maintenance page for the duration of this upgrade.
* Back up the old instance of postgresql with pg_dump. The dump file was copied to testdb for safekeeping. (17 minutes total).
* An ansible script was run, which shut down the old postgresql instance, ran 'pg_upgrade', then removed the 9.4 debian libraries once this was completed. New postgresql.conf files were installed. The new database was started up. (about 6 minutes)
* /usr/lib/postgresql/9.5/bin/vacuumdb --all --analyze-only was run, necessary after a pg_upgrade. (6 minutes)
* db1 was rebooted to assure that the database came up correctly, unattended. (It did so.)
* apt-get upgrade was performed to bring all non-postgresql libraries up to date, and a second reboot was performed.

At this point the workers on web1 and web2 were ready to be brought up. I did so at approximately 11:35. Initial access was slow and non-optimal because the database required warming for the first time after its upgrade. By about 11:45, access times were approaching a more normal range.

An all clear was sent through status.weasyl.com (status cleared), and a tweet to our userbase, at about 11:50-11:55 pm. I also informed gitter.im of the completion of the maintenance, in its IM window.

Again, I apologize for not seeing there was a request for the full plan in this issue. I looked here after the upgrade's completion to be able to inform on this GitHub issue and that of #54 that it *had* been done.

**Comment by skylerbunny** [comment]
Now that we can do something about it, the oft-repeated type of error in our database's logfile is this:

2016-06-20 10:27:44 PDT [721-7] weasyl@weasyl ERROR:  duplicate key value violates unique constraint "views_pkey"
2016-06-20 10:27:44 PDT [721-8] weasyl@weasyl DETAIL:  Key (viewer, targetid, type)=(user:89052, 1239805, 110) already exists.
2016-06-20 10:27:44 PDT [721-9] weasyl@weasyl STATEMENT:  INSERT INTO views (viewer, targetid, type) VALUES ('user:89052', 1239805, 110)
